# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.CharField(max_length=255, verbose_name='Короткий опис')),
                ('description_image', models.CharField(default='', max_length=255)),
                ('content', markdownx.models.MarkdownxField(verbose_name='Контент')),
                ('published', models.BooleanField(default=True, verbose_name='Опубліковано?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('last_accessed', models.DateTimeField(verbose_name='Останній перегляд')),
                ('last_accessed_ip', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP-адреса останнього відвідувача')),
                ('original_link', models.URLField(default='', verbose_name='Посилання на оригінал')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Назва тегу')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
